package one.system42.solnode;
import android.app.*;
import android.content.*;
import android.os.*;
import android.graphics.Color;
import android.view.*;
import android.widget.*;
import org.json.*;
public final class MainActivity extends Activity {
 private final int BG=Color.rgb(12,19,24),PANEL=Color.rgb(23,35,43),INK=Color.rgb(225,238,240),ACCENT=Color.rgb(96,220,197);
 private LinearLayout root,body; private TextView connection; private ToolRegistry tools; private String tab="CHAT"; private boolean bound; private ConversationStore history; private TextView transcript,chatState; private Button send; private EditText prompt; private SolApiClient api; private boolean busy; private String busyLabel="RECEIVING / SOL API"; private String live=""; private InferenceManager inference; private int requestId; private String selectedMode="AUTO",selectedProfile="reasoning";
 private ServiceConnection service=new ServiceConnection(){
  public void onServiceConnected(ComponentName n,IBinder b){tools=((SolNodeService.LocalBinder)b).tools();inference=((SolNodeService.LocalBinder)b).inference();connection.setText("LOCAL SERVICE  /  READY");show(tab);}
  public void onServiceDisconnected(ComponentName n){tools=null;connection.setText("LOCAL SERVICE  /  DISCONNECTED");}
 };
 public void onCreate(Bundle state){super.onCreate(state); history=new ConversationStore(this); if(state!=null)tab=state.getString("tab","CHAT");
  root=new LinearLayout(this); root.setOrientation(1);root.setPadding(dp(16),dp(16),dp(16),dp(8));root.setBackgroundColor(BG);setContentView(root);
  TextView title=label("SOL NODE",28,ACCENT);root.addView(title);connection=label("CONNECTING LOCAL SERVICE",12,INK);root.addView(connection);
  ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(1);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout nav=new LinearLayout(this);for(final String t:new String[]{"CHAT","NODE","TOOLS","SETTINGS"}){Button b=button(t,new View.OnClickListener(){public void onClick(View v){show(t);}});b.setTextSize(12);nav.addView(b,new LinearLayout.LayoutParams(0,dp(52),1));}root.addView(nav);
  bound=bindService(new Intent(this,SolNodeService.class),service,BIND_AUTO_CREATE);show(tab);
 }
 private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
 private TextView label(String s,int size,int color){TextView v=new TextView(this);v.setText(s);v.setTextColor(color);v.setTextSize(size);v.setPadding(0,dp(9),0,dp(9));return v;}
 private Button button(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextColor(INK);b.setOnClickListener(l);return b;}
 private void text(String s){body.addView(label(s,16,INK));}
 private void card(String key,String value){LinearLayout c=new LinearLayout(this);c.setOrientation(1);c.setPadding(dp(14),dp(4),dp(14),dp(8));c.setBackgroundColor(PANEL);c.addView(label(key,12,ACCENT));c.addView(label(value,21,INK));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(9),0,0);body.addView(c,p);}
 private String mib(long n){return String.format(java.util.Locale.US,"%.0f MiB",n/1048576.0);}
 private void show(String t){tab=t;body.removeAllViews();
  if(t.equals("NODE")){text("DEVICE / LIVE SNAPSHOT"); if(tools==null){text("Waiting for local service…");return;}try{JSONObject s=tools.execute("device.status");card(s.getString("model"),"Android "+s.getString("android")+"  ·  API "+s.getInt("api"));card("BATTERY",s.optString("battery_percent","unknown")+"%  /  "+(s.getBoolean("charging")?"Charging":"On battery"));card("AVAILABLE",mib(s.getLong("storage_available_bytes"))+" storage\n"+mib(s.getLong("ram_available_bytes"))+" RAM");card("NETWORK",s.getString("network_type")+" / "+(s.getBoolean("network_connected")?"connected":"offline"));text("Network connection does not prove SOL API reachability.\nCamera: no permission / not opened by this app.\nSAAYN: app-owned native bridge; use Tools to run. Existing SSH runtime preserved.");body.addView(button("REFRESH",new View.OnClickListener(){public void onClick(View v){show("NODE");}}));}catch(Exception e){text("Status unavailable: "+e.getMessage());}}
  else if(t.equals("CHAT")){renderChat();}
  else if(t.equals("TOOLS")){text("CAPABILITIES / LOCAL ONLY");for(final String id:ToolRegistry.IDS){body.addView(button(id,new View.OnClickListener(){public void onClick(View v){try{new AlertDialog.Builder(MainActivity.this).setTitle(id).setMessage(tools.execute(id).toString(2)).setPositiveButton("CLOSE",null).show();}catch(Exception e){Toast.makeText(MainActivity.this,"Unavailable",0).show();}}}));}body.addView(button("SAAYN / NEXT TOKEN",new View.OnClickListener(){public void onClick(View v){askInference("Hello");}}));text("Remote execution: disabled\nCamera, files and shell: not registered.\nSAAYN requires confirmation; reads existing model tensors.\nGUI and local console share the local service.");}
  else{ text("SETTINGS");final EditText name=new EditText(this);name.setTextColor(INK);name.setSingleLine(true);name.setText(getPreferences(0).getString("node_label","sol-s4"));text("Local node label (not a registered cloud identity)");body.addView(name);body.addView(button("SAVE LABEL",new View.OnClickListener(){public void onClick(View v){String s=name.getText().toString().trim();if(s.length()>0&&s.length()<=64){getPreferences(0).edit().putString("node_label",s).commit();Toast.makeText(MainActivity.this,"Saved locally",0).show();}}}));final CheckBox persist=new CheckBox(this);persist.setTextColor(INK);persist.setText("Keep conversation context on public SOL server");persist.setChecked(getPreferences(0).getBoolean("persist",false));persist.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener(){public void onCheckedChanged(CompoundButton b,boolean checked){getPreferences(0).edit().putBoolean("persist",checked).commit();}});body.addView(persist);text("Public endpoint: "+(SolApiClient.BASE.length()==0?"not configured":SolApiClient.BASE)+"\nOff: each cloud request is stateless. Local transcript stays on this phone.\nPublic SOL currently has no user login in its chat contract. Do not submit private content without considering server storage.\nSOL Node 0.3.0\nNo camera, shell, remote tools or boot autostart. Existing SSH remains separate.");}
 }
 private void askInference(String initial){
  if(busy||inference==null){Toast.makeText(this,"Worker unavailable or busy",0).show();return;}
  final EditText input=new EditText(this);input.setText(initial);input.setTextColor(INK);
  new AlertDialog.Builder(this).setTitle("Run SAAYN locally?").setMessage("One next token. Reads the existing model cache; may use substantial RAM for up to 120 seconds. No cloud request. Printable ASCII, up to 16 context tokens.").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("RUN LOCALLY",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int which){
   final String prompt=input.getText().toString();final String session=history.session();final int ticket=inference.prepare();busy=true;busyLabel="LOCAL / computing next token";live="LOCAL / computing next token…";show("CHAT");final int id=++requestId;
   new Thread(new Runnable(){public void run(){try{final JSONObject result=inference.run(prompt,ticket);runOnUiThread(new Runnable(){public void run(){if(id!=requestId)return;getPreferences(0).edit().putString("last_inference",result.toString()).commit();history.append(session,"LOCAL / SAAYN","Token: "+result.optString("token")+"\nToken ID: "+result.optInt("token_id")+"\nNative runtime: "+result.optDouble("elapsed_seconds")+" s\nContext tokens: "+result.optInt("context_tokens")+"\n"+result.optString("progress"));finishChat();}});}catch(final Exception e){runOnUiThread(new Runnable(){public void run(){if(id!=requestId)return;history.append(session,"LOCAL ERROR",e.getMessage());finishChat();}});}}},"sol-inference").start();
  }}).show();
 }

 private void askLocalChat(final String session){
  if(busy||inference==null){Toast.makeText(this,"Local worker unavailable",0).show();return;}
  new AlertDialog.Builder(this).setTitle("Generate locally with SAAYN?").setMessage("GPT-2 text generation on this S4. Up to 24 new tokens / 10 minutes; 16-token sliding context. Not instruction-tuned. No cloud request.").setNegativeButton("CANCEL",null).setPositiveButton("GENERATE LOCALLY",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int which){
   StringBuilder context=new StringBuilder(DialoguePolicy.PRIMER);JSONArray messages=history.messages(session);for(int i=0;i<messages.length();i++){JSONObject m=messages.optJSONObject(i);String role=m.optString("role");if(role.equals("YOU"))context.append("User: ").append(DialoguePolicy.content(m.optString("text"))).append(" ");else if(role.equals("LOCAL / SAAYN CHAT")&&!DialoguePolicy.bad(m.optString("text")))context.append("Assistant: ").append(DialoguePolicy.content(m.optString("text").split("\n\n\\[Generated")[0])).append(" ");}context.append("Assistant:");String input=context.toString();if(input.length()>1024)input=input.substring(input.length()-1024);final String modelPrompt=input;
   final int ticket=inference.prepare();final int id=++requestId;busy=true;busyLabel="LOCAL / generating on S4";live="";show("CHAT");
   new Thread(new Runnable(){public void run(){try{final JSONObject result=inference.generate(modelPrompt,ticket,new InferenceManager.Listener(){public void update(final String text,final int count){runOnUiThread(new Runnable(){public void run(){if(id!=requestId)return;live=text;if(transcript!=null)transcript.setText(history.display()+"LOCAL / SAAYN CHAT\n"+live);if(chatState!=null)chatState.setText("LOCAL / "+count+" tokens generated");}});}});runOnUiThread(new Runnable(){public void run(){if(id!=requestId)return;getPreferences(0).edit().putString("last_generation",result.toString()).commit();history.append(session,"LOCAL / SAAYN CHAT",DialoguePolicy.clean(result.optString("text"))+"\n\n[Generated "+result.optInt("generated_tokens")+" tokens in "+result.optDouble("elapsed_seconds")+" s; "+result.optString("stop_reason")+"]");finishChat();}});}catch(final Exception e){runOnUiThread(new Runnable(){public void run(){if(id!=requestId)return;history.append(session,"LOCAL ERROR",(live.length()>0?"Partial generation:\n"+live+"\n\n":"")+e.getMessage());finishChat();}});}}},"sol-local-chat").start();
  }}).show();
 }
 private void renderChat(){
  text("SOL CHAT  /  PUBLIC API + LOCAL TOOLS");
  LinearLayout row=new LinearLayout(this);
  final Spinner mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"AUTO","LOCAL","SOL API"}));row.addView(mode,new LinearLayout.LayoutParams(0,dp(48),1));
  final Spinner profile=new Spinner(this);profile.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"reasoning","text_fast"}));row.addView(profile,new LinearLayout.LayoutParams(0,dp(48),1));mode.setSelection(selectedMode.equals("LOCAL")?1:selectedMode.equals("SOL API")?2:0);profile.setSelection(selectedProfile.equals("text_fast")?1:0);body.addView(row);
  chatState=label(busy?busyLabel:"IDLE / Local commands available",12,ACCENT);body.addView(chatState);
  transcript=label(history.display()+live,16,INK);transcript.setTextIsSelectable(true);ScrollView messages=new ScrollView(this);messages.addView(transcript);body.addView(messages,new LinearLayout.LayoutParams(-1,dp(210)));
  prompt=new EditText(this);prompt.setTextColor(INK);prompt.setHint("Message SOL or /status");prompt.setMinLines(2);body.addView(prompt);
  send=button(busy?"CANCEL":"SEND",new View.OnClickListener(){public void onClick(View v){if(busy){cancelChat();return;}submit(prompt.getText().toString().trim(),mode.getSelectedItem().toString(),profile.getSelectedItem().toString());}});body.addView(send);
  body.addView(button("FULL TRANSCRIPT",new View.OnClickListener(){public void onClick(View v){final Dialog d=new Dialog(MainActivity.this);d.setTitle("SOL / FULL CONVERSATION");ScrollView scroll=new ScrollView(MainActivity.this);scroll.setBackgroundColor(BG);TextView all=label(history.display()+live,14,INK);all.setPadding(dp(14),dp(10),dp(14),dp(10));all.setTextIsSelectable(true);scroll.addView(all);d.setContentView(scroll);d.show();d.getWindow().setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(BG));d.getWindow().setLayout(-1,-1);}}));
  body.addView(button("CONVERSATIONS",new View.OnClickListener(){public void onClick(View v){if(busy)return;final String[] ids=history.sessions();String[] labels=new String[ids.length+1];labels[0]="+ New conversation";for(int i=0;i<ids.length;i++){JSONArray a=history.messages(ids[i]);labels[i+1]=a.length()>0?a.optJSONObject(0).optString("text").substring(0,Math.min(45,a.optJSONObject(0).optString("text").length())):"Empty conversation";}new AlertDialog.Builder(MainActivity.this).setTitle("Local conversations").setItems(labels,new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int which){if(which==0)history.create();else history.select(ids[which-1]);show("CHAT");}}).show();}}));
 }
 private void submit(final String message,String mode,final String profile){
  selectedMode=mode;selectedProfile=profile;if(message.length()==0)return;if(message.length()>4000){chatState.setText("Maximum 4,000 characters");return;}
  final String session=history.session();history.append(session,"YOU",message);prompt.setText("");
  if(mode.equals("LOCAL")&&!message.startsWith("/")){askLocalChat(session);return;}
  if(message.startsWith("/saayn ")){askInference(message.substring(7));return;}
  if(message.startsWith("/")||mode.equals("LOCAL")){
   String id=message.equals("/status")?"device.status":message.equals("/battery")?"device.battery":message.equals("/storage")?"device.storage":message.equals("/network")?"device.network":"unsupported";
   try{history.append(session,"LOCAL",tools==null?"Service unavailable":tools.execute(id).toString(2));}catch(Exception e){history.append(session,"LOCAL","Available: /status /battery /storage /network /saayn Hello.");}show("CHAT");return;
  }
  busy=true;busyLabel="RECEIVING / SOL API";live="";api=new SolApiClient(this);final SolApiClient client=api;final int id=++requestId;final boolean persist=getPreferences(0).getBoolean("persist",false);send.setText("CANCEL");chatState.setText("CONNECTING / SOL API");transcript.setText(history.display());
  new Thread(new Runnable(){public void run(){try{client.chat(message,session,profile,persist,new SolApiClient.Events(){public void event(final JSONObject event){runOnUiThread(new Runnable(){public void run(){if(id!=requestId)return;String type=event.optString("type");if(type.equals("delta")){live+=event.optString("delta");if(live.length()>65536){cancelChat();return;}if(transcript!=null)transcript.setText(history.display()+"SOL API\n"+live);}else if(type.equals("status")){if(chatState!=null)chatState.setText("SOL API / "+event.optString("state"));}else if(type.equals("done")){String answer=event.optString("message",live);String label="SOL API";if(event.optBoolean("fallback_grounding_used")||event.optBoolean("fallback_answer"))label+=" / FALLBACK";history.append(session,label,answer);finishChat();}else if(type.equals("error")){history.append(session,"API ERROR",event.optString("error"));finishChat();}}});}});}catch(final Exception e){runOnUiThread(new Runnable(){public void run(){if(id!=requestId)return;history.append(session,"CONNECTION ERROR",(live.length()>0?"Partial response:\n"+live+"\n\n":"")+e.getClass().getSimpleName()+": "+e.getMessage()+"\nNo automatic retry. Local tools remain available.");finishChat();}});}}},"sol-chat").start();
 }
 private void finishChat(){busy=false;live="";api=null;if(tab.equals("CHAT"))show("CHAT");}
 private void cancelChat(){++requestId;if(inference!=null)inference.cancel();if(api!=null){final SolApiClient old=api;new Thread(new Runnable(){public void run(){old.cancel();}}).start();}history.append(history.session(),"CANCELLED",live.length()>0?live:"Request cancelled locally; server may still finish.");finishChat();}
 public void onSaveInstanceState(Bundle s){s.putString("tab",tab);super.onSaveInstanceState(s);}
 public void onDestroy(){if(busy)cancelChat();if(bound)unbindService(service);super.onDestroy();}
}
